engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 50

  fixme:
    enabled: false

  markdownlint:
    enabled: true

  pep8:
    enabled: true
    checks:
      E501:
        enabled: false

  radon:
    enabled: true
    config:
      threshold: "C"

ratings:
  paths:
  - "**.md"
  - "**.py"

exclude_paths:
- docs/build/*
