language: python

cache: pip

python:
  - "2.7"

before_install:
  # install test dependencies
  - pip install --upgrade codecov
  - pip install --upgrade pytest-cov
  - pip install --upgrade responses

install:
  # install dependencies
  - pip install --upgrade requests
  # important: install the library itself
  - pip install --upgrade -e .

script:
  # run tests
  py.test --cov pyunsplash --cov-report term-missing --cov-report xml

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  # codecov  # python specific?

deploy:
  provider: pypi
  edge: true
  user: salvoventura
  password:
    secure: Kf0bhE9b+ZZr0gUOMkuYZhWE0wBihYoQRhy+ytgi8RyLtqEjCry3be6EShLK3xnoiwNmnjR1/IICn9QeR28LIT7fSB6JLJW+BVUZtVKf96McKYEx9ANTa9CDD9hqyXS3BCtJDnF3Bv6Ix8lnf/AJ7xmpERWiwCRFRSlNRMx61Wz4TLgaByiM6caEujbgV3y2ogDrTw8og95KFG3gvvehSKMmvGQUoX6mnLCTTEe/uPkXfNnjMS73fQ+vl8NTnjhhIFmGzDoljMbZYAdrZxgJHjlrmkU1mnahIxs6Raf0UujDBF7Lz4c2CCCC0HW4ce67kQTuki5cJ924aFOt3ZW334VFaPa4ACiWIGNxJ5wDYRHsY7YTnxrXBl2UnVmVspQhxMYGKInWQcWWHcUspOjVxYzS8K6fTXFH/y8iDWf1exs0WAA3aNWNBS+LDXZd+FytoieM2z00Hf6spnhsPgqk2piu44vP3D0ppQxCm9u0XrWaqMeeiyFEZrLXtUNQi/nznYWMMh64U6CEfyEN5NBaqk7nCDoq3a3cQ1WgcbmQ084OLBMvWDLxKrp/k+aoUD1ApZDB+UeiqwM/uZiHsVJISWtE2ZVj6Ao2Dl/pZmPMuj7HVUm3F+4nZpQSGaFFVTHgKqYHKRu5SVPWpiijgcQwGDw25vJsY7tI8aR+34kjrm8=
  on:
    tags: true
    all_branches: true
