language: python

python:
  - "2.7"

script:
  - touch foo

deploy:
  provider: pypi
  user: salvoventura
  password:
    secure: bl+Ry8sBM7dqjFmgoq36cJ/nHWUbBkJKufNKd2FHzCCAVnMUuhxZ4INgROvxGvoDfSGrGmDr9r9pa1ufkEI8x+vEMirwIXbeiRfbNUxx+xA3jqFvT+1yBHmNXUwibnJGtW2vuAIUMGP8Nqkg0dCtT0/a/wC7AbIIpL15Mwfo87LFZI/aOui2VW/ASdoLSg0JaCgCOF0ZWnDr7LgOcxfggKWUmyZNU0akE5MENep/HVTjYcrOvy+DH+O5o9FNM0ne+mYmGFdpPpNSWfUwnpt4Pv1ri4cYGE4ktrmuXlYbOkBeDs2qSsQyQslNzranuL6LZhLbefyX76cpnCnqEmTcXIz3k3g2+DAS4pYAhm/MuRYi7uKLdROP32vDDL4zcrqrBZ4GxJ3GRhEDMAY+TlgRm8bTfkDgliUq/qB4uNrVsO2DKWunnp8lz2aJ/UMpiDTML0fE6NDXAynggn9ugvB3pjHNkqeJB0dl19oWuFTVPLbpvrmMgynY0813A/fX0LbaxQc0Mv1wRI18utgCs5/8vRg/gXB65TKXaLh9ati4OwuZ1fJ8BCCX5H+yujoaA+ca1VjfeaNReBOQwTwWcBbNceyVmRMmY0Eq7TIEjXkUjQrX31Ww1DLPSJINhnPNFNvK5CMTOLxtN8K4iH3C9EGQ6QEySlw2PfglWA4XL9/xQlA=
  on:
    tags: true
    branch: master
